apiVersion: v1
kind: Pod
metadata:
  name: busybox-nginx-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo Hello World! && sleep 3600']
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080
    #chudkhv
